export const GET_PIZZA_LIST = "GET_PIZZA_LIST";
export const GET_SNACK_LIST = "GET_SNACK_LIST";
export const GET_WATER_LIST = "GET_WATER_LIST";
export const CHANGE_CURRENT_PAGE = "CHANGE_CURRENT_PAGE";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const CHANGE_COUNT_PRODUCT = "CHANGE_COUNT_PRODUCT";
export const CHANGE_MODAL_VUE = "CHANGE_MODAL_VUE";
