mov inputstr ah //Кладем адрес строки в ah
int 15 //...
int 13 //...
mov ah dh //Перем. знач. регистра ah в dh
mov inputstr ah //Кладем адрес строки в ah
int 15 //...
int 13 //...
mov ah eh //...
mov dh eax //...
mov eh ebx //...
div ebx //Произв. деление регистра ah/eax (в данном случ. eax)
mov outstr ah //...
int 15 //...
int 12 //Вывод числа из регистра eax на экран
int 10 //...
inputstr:
.string Input number:
outstr:
.string Result: